### ISSUE TITLE
Instacrash on Lenovo Phab2Pro (Android 6.0.1, Tango Core 1.55)

### ISSUE THREAD

**Issue by BKcore** [googlevr/chromium-webar#11]
ChromiumAR crashes on load on my Lenovo Phab2Pro (Android 6.0.1, Tango 1.55)

The version reported by the Tango Core app is 1.55:2017.06.23.

Here's the actual error from logcat:
```
FATAL EXCEPTION: main
Process: org.chromium.android_webview.shell, PID: 8936
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "TangoService_updateTextureExternalOesForBuffer" referenced by "/data/app/org.chromium.android_webview.shell-1/lib/arm/libtango_chromium.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.chromium.android_webview.shell.TangoJniNative.initialize(TangoJniNative.java:40)
	at org.chromium.android_webview.shell.AwShellActivity.onCreate(AwShellActivity.java:520)
	at android.app.Activity.performCreate(Activity.java:6285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
	at android.app.ActivityThread.access$900(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Is there something I'm missing?
Is there a way to get the v1.45 APK of Tango Core somewhere to test?

**Comment by judax** [comment]
I have a Lenovo Phab 2 Pro with Tango core 1.55 (the exact version you mention) and it works. This is pretty strange indeed. I do not know what else to say TBH.

**Comment by BKcore** [comment]
I ended up installing again through `adb` instead of directly from the phone and now it works. I may have ended with a corrupted download.
Closing, thanks!
